export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as Main} from './Main'
export {default as Portfolio} from './Portfolio'
export {default as Footer} from './Footer'